CLASS zcl_pia_race DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    CLASS-METHODS one RETURNING VALUE(r) TYPE i.
ENDCLASS.

CLASS zcl_pia_race IMPLEMENTATION.
  METHOD one.
    r = 1.
  ENDMETHOD.
ENDCLASS.
